// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oevnlfevmiwsmenbyceb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ldm5sZmV2bWl3c21lbmJ5Y2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODA3MzYsImV4cCI6MjA1ODg1NjczNn0.Qng5GzCZdzpvcgGmD-XR3qriYPNgIat9-piPmDVrd7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);